//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moja_biblioteczka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ksiazki
    {
        public int IDKsiazki { get; set; }
        public string Nazwisko { get; set; }
        public string Imie { get; set; }
        public string Tytul { get; set; }
        public Nullable<int> IDPolki { get; set; }
        public Nullable<int> Ocena { get; set; }
        public string Uwagi { get; set; }
    
        public virtual Polki Polki { get; set; }
    }
}
